// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://trojfnjtcwjitlziurkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyb2pmbmp0Y3dqaXRseml1cmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTMwMDEsImV4cCI6MjA3MzM4OTAwMX0.ShdcNpTX_59g0M5dqzwf_mnkoK5AP-nvwTaX60KNlhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});